services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/amd64}
        TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    image: docker.io/tolgahasandur/flikr-caption-generator:backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/amd64}
        TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    image: docker.io/tolgahasandur/flikr-caption-generator:frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
